### ISSUE TITLE
How to use my own datasets?

### ISSUE THREAD

**Issue by ScottishFold007** [AndreasMadsen/python-textualheatmap#1]
Hello! Your project is great! I want to use my own data set. How does this work?
Looking forward to your reply！

**Comment by AndreasMadsen** [comment]
@ScottishFold007 What do you mean? You construct a data structure as shown in https://github.com/AndreasMadsen/python-textualheatmap#example, how you do that depends on your application. Essentially the data structure is `List[List[{"heat": List[float], "token": str, "meta": List[str]}]]`.

**Comment by AndreasMadsen** [comment]
I made a notebook that explains it in detail. https://colab.research.google.com/github/AndreasMadsen/python-textualheatmap/blob/master/notebooks/huggingface_bert_example.ipynb

**Comment by ScottishFold007** [comment]
wonderful!
